// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: component_prices.sql

package db

import (
	"context"
)

const getComponentPriceByNormalizedName = `-- name: GetComponentPriceByNormalizedName :one
SELECT id, name, name_normalized, category, price_amount, price_currency, sample_count, scraped_at
FROM component_prices
WHERE name_normalized = $1
`

func (q *Queries) GetComponentPriceByNormalizedName(ctx context.Context, nameNormalized string) (ComponentPrice, error) {
	row := q.db.QueryRow(ctx, getComponentPriceByNormalizedName, nameNormalized)
	var i ComponentPrice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Category,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.SampleCount,
		&i.ScrapedAt,
	)
	return i, err
}

const listStaleComponentPrices = `-- name: ListStaleComponentPrices :many
SELECT id, name, name_normalized, category, price_amount, price_currency, sample_count, scraped_at
FROM component_prices
WHERE scraped_at < NOW() - make_interval(secs => $1)
`

func (q *Queries) ListStaleComponentPrices(ctx context.Context, secs float64) ([]ComponentPrice, error) {
	rows, err := q.db.Query(ctx, listStaleComponentPrices, secs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComponentPrice
	for rows.Next() {
		var i ComponentPrice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Category,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.SampleCount,
			&i.ScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComponentPrice = `-- name: UpsertComponentPrice :exec
INSERT INTO component_prices (name, name_normalized, category, price_amount, price_currency, sample_count, scraped_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (name_normalized) DO UPDATE SET
    price_amount   = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    sample_count   = EXCLUDED.sample_count,
    scraped_at     = NOW()
`

type UpsertComponentPriceParams struct {
	Name           string
	NameNormalized string
	Category       string
	PriceAmount    float64
	PriceCurrency  string
	SampleCount    int32
}

func (q *Queries) UpsertComponentPrice(ctx context.Context, arg UpsertComponentPriceParams) error {
	_, err := q.db.Exec(ctx, upsertComponentPrice,
		arg.Name,
		arg.NameNormalized,
		arg.Category,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.SampleCount,
	)
	return err
}
