// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: listings.sql

package db

import (
	"context"
	"time"
)

const getListingByID = `-- name: GetListingByID :one
SELECT id, url, url_hash, title, description, raw_price, raw_html, scraped_at,
       title_normalized, price_amount, price_currency, condition, category, location_city,
       specs, deal_score, deal_reasoning, is_suspicious, suspicious_reason,
       market_score, enrichment_status, enriched_at
FROM listings
WHERE id = $1
`

type GetListingByIDRow struct {
	ID               int64
	Url              string
	UrlHash          string
	Title            string
	Description      *string
	RawPrice         *string
	RawHtml          *string
	ScrapedAt        *time.Time
	TitleNormalized  *string
	PriceAmount      *float64
	PriceCurrency    *string
	Condition        *string
	Category         *string
	LocationCity     *string
	Specs            []byte
	DealScore        *int32
	DealReasoning    *string
	IsSuspicious     *bool
	SuspiciousReason *string
	MarketScore      *float64
	EnrichmentStatus string
	EnrichedAt       *time.Time
}

func (q *Queries) GetListingByID(ctx context.Context, id int64) (GetListingByIDRow, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i GetListingByIDRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlHash,
		&i.Title,
		&i.Description,
		&i.RawPrice,
		&i.RawHtml,
		&i.ScrapedAt,
		&i.TitleNormalized,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Condition,
		&i.Category,
		&i.LocationCity,
		&i.Specs,
		&i.DealScore,
		&i.DealReasoning,
		&i.IsSuspicious,
		&i.SuspiciousReason,
		&i.MarketScore,
		&i.EnrichmentStatus,
		&i.EnrichedAt,
	)
	return i, err
}

const getListings = `-- name: GetListings :many
SELECT id, url, url_hash, title, description, raw_price, raw_html, scraped_at,
       title_normalized, price_amount, price_currency, condition, category, location_city,
       specs, deal_score, deal_reasoning, is_suspicious, suspicious_reason,
       market_score, enrichment_status, enriched_at
FROM listings
ORDER BY scraped_at DESC
LIMIT $1 OFFSET $2
`

type GetListingsParams struct {
	Limit  int32
	Offset int32
}

type GetListingsRow struct {
	ID               int64
	Url              string
	UrlHash          string
	Title            string
	Description      *string
	RawPrice         *string
	RawHtml          *string
	ScrapedAt        *time.Time
	TitleNormalized  *string
	PriceAmount      *float64
	PriceCurrency    *string
	Condition        *string
	Category         *string
	LocationCity     *string
	Specs            []byte
	DealScore        *int32
	DealReasoning    *string
	IsSuspicious     *bool
	SuspiciousReason *string
	MarketScore      *float64
	EnrichmentStatus string
	EnrichedAt       *time.Time
}

func (q *Queries) GetListings(ctx context.Context, arg GetListingsParams) ([]GetListingsRow, error) {
	rows, err := q.db.Query(ctx, getListings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListingsRow
	for rows.Next() {
		var i GetListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlHash,
			&i.Title,
			&i.Description,
			&i.RawPrice,
			&i.RawHtml,
			&i.ScrapedAt,
			&i.TitleNormalized,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Condition,
			&i.Category,
			&i.LocationCity,
			&i.Specs,
			&i.DealScore,
			&i.DealReasoning,
			&i.IsSuspicious,
			&i.SuspiciousReason,
			&i.MarketScore,
			&i.EnrichmentStatus,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertListing = `-- name: InsertListing :one
INSERT INTO listings (url, url_hash, title, description, raw_price, raw_html)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (url_hash) DO NOTHING
RETURNING id
`

type InsertListingParams struct {
	Url         string
	UrlHash     string
	Title       string
	Description *string
	RawPrice    *string
	RawHtml     *string
}

func (q *Queries) InsertListing(ctx context.Context, arg InsertListingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertListing,
		arg.Url,
		arg.UrlHash,
		arg.Title,
		arg.Description,
		arg.RawPrice,
		arg.RawHtml,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resetListingEnrichment = `-- name: ResetListingEnrichment :exec
UPDATE listings
SET enriched_at = NULL, enrichment_status = 'pending'
WHERE id = $1
`

func (q *Queries) ResetListingEnrichment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetListingEnrichment, id)
	return err
}

const updateListingEnrichment = `-- name: UpdateListingEnrichment :exec
UPDATE listings SET
    title_normalized  = $2,
    price_amount      = $3,
    price_currency    = $4,
    condition         = $5,
    category          = $6,
    location_city     = $7,
    specs             = $8,
    deal_score        = $9,
    deal_reasoning    = $10,
    is_suspicious     = $11,
    suspicious_reason = $12,
    market_score      = $13,
    enrichment_status = 'done',
    enriched_at       = NOW()
WHERE id = $1 AND enriched_at IS NULL
`

type UpdateListingEnrichmentParams struct {
	ID               int64
	TitleNormalized  *string
	PriceAmount      *float64
	PriceCurrency    *string
	Condition        *string
	Category         *string
	LocationCity     *string
	Specs            []byte
	DealScore        *int32
	DealReasoning    *string
	IsSuspicious     *bool
	SuspiciousReason *string
	MarketScore      *float64
}

func (q *Queries) UpdateListingEnrichment(ctx context.Context, arg UpdateListingEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateListingEnrichment,
		arg.ID,
		arg.TitleNormalized,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Condition,
		arg.Category,
		arg.LocationCity,
		arg.Specs,
		arg.DealScore,
		arg.DealReasoning,
		arg.IsSuspicious,
		arg.SuspiciousReason,
		arg.MarketScore,
	)
	return err
}
