// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES ($1, $2) RETURNING id
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	var id int64
	err := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash).Scan(&id)
	return id, err
}

const getUnverifiedUsers = `-- name: GetUnverifiedUsers :many
SELECT id, username, password_hash, created_at, is_verified, role FROM users WHERE is_verified = false OR is_verified IS NULL ORDER BY id
`

func (q *Queries) GetUnverifiedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUnverifiedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.IsVerified,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, is_verified, role FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsVerified,
		&i.Role,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET is_verified = $1 WHERE id = $2 RETURNING is_verified
`

type VerifyUserParams struct {
	IsVerified sql.NullBool
	ID         int64
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, arg.IsVerified, arg.ID)
	var is_verified sql.NullBool
	err := row.Scan(&is_verified)
	return is_verified, err
}
